/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UiOfGame;

import java.awt.CardLayout;
import loginandregister.Model;
//import javax.swing;

/**
 *
 * @author maria
 */
public class UIGameXO extends javax.swing.JFrame {

    /**
     * Creates new form ProjectXO
     */
    UiOfGameControl control;

    public UIGameXO() {
        initComponents();
        control = new UiOfGameControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpParent = new javax.swing.JPanel();
        jpMainScreen = new javax.swing.JPanel();
        bPlayWithFriend = new javax.swing.JButton();
        bPlayNetwork = new javax.swing.JButton();
        bPlayWithPc = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        lbScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLWinUi = new javax.swing.JLabel();
        jLLoseUi = new javax.swing.JLabel();
        jLDrawUi = new javax.swing.JLabel();
        jtUserNameUi = new javax.swing.JLabel();
        jpPlayWithPerson = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bBack = new javax.swing.JButton();
        jpNetwork = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bBackNewtwork = new javax.swing.JButton();
        jpPlaywithPc = new javax.swing.JPanel();
        lPlayPC = new javax.swing.JLabel();
        bBackPerson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpParent.setBackground(new java.awt.Color(153, 153, 153));
        jpParent.setToolTipText("");
        jpParent.setName(""); // NOI18N
        jpParent.setLayout(new java.awt.CardLayout());

        jpMainScreen.setBackground(new java.awt.Color(0, 0, 51));

        bPlayWithFriend.setBackground(new java.awt.Color(255, 102, 0));
        bPlayWithFriend.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bPlayWithFriend.setForeground(new java.awt.Color(0, 0, 102));
        bPlayWithFriend.setText("Play With Friends");
        bPlayWithFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayWithFriendActionPerformed(evt);
            }
        });

        bPlayNetwork.setBackground(new java.awt.Color(255, 102, 0));
        bPlayNetwork.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bPlayNetwork.setForeground(new java.awt.Color(0, 0, 102));
        bPlayNetwork.setText("NetWorks");
        bPlayNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayNetworkActionPerformed(evt);
            }
        });

        bPlayWithPc.setBackground(new java.awt.Color(255, 102, 0));
        bPlayWithPc.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bPlayWithPc.setForeground(new java.awt.Color(0, 0, 102));
        bPlayWithPc.setText("Play With PC");
        bPlayWithPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayWithPcActionPerformed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(255, 102, 0));
        bExit.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        bExit.setForeground(new java.awt.Color(0, 0, 102));
        bExit.setText("Exit Game");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        lbUserName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(0, 0, 102));
        lbUserName.setText("User Name :");

        lbScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbScore.setForeground(new java.awt.Color(0, 0, 102));
        lbScore.setText("Win :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Lose :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Draw :");

        jtUserNameUi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtUserNameUiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbScore)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLWinUi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtUserNameUi, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLLoseUi, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLDrawUi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jtUserNameUi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLLoseUi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLWinUi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLDrawUi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbScore, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jpMainScreenLayout = new javax.swing.GroupLayout(jpMainScreen);
        jpMainScreen.setLayout(jpMainScreenLayout);
        jpMainScreenLayout.setHorizontalGroup(
            jpMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMainScreenLayout.createSequentialGroup()
                .addGroup(jpMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMainScreenLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMainScreenLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jpMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bPlayNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPlayWithFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPlayWithPc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMainScreenLayout.setVerticalGroup(
            jpMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainScreenLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bPlayWithPc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bPlayWithFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPlayNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpParent.add(jpMainScreen, "card2");

        jpPlayWithPerson.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Play With Person");

        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPlayWithPersonLayout = new javax.swing.GroupLayout(jpPlayWithPerson);
        jpPlayWithPerson.setLayout(jpPlayWithPersonLayout);
        jpPlayWithPersonLayout.setHorizontalGroup(
            jpPlayWithPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayWithPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jpPlayWithPersonLayout.setVerticalGroup(
            jpPlayWithPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayWithPersonLayout.createSequentialGroup()
                .addGroup(jpPlayWithPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPlayWithPersonLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPlayWithPersonLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jpParent.add(jpPlayWithPerson, "card5");

        jpNetwork.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Play Network");

        bBackNewtwork.setText("Back");
        bBackNewtwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackNewtworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNetworkLayout = new javax.swing.GroupLayout(jpNetwork);
        jpNetwork.setLayout(jpNetworkLayout);
        jpNetworkLayout.setHorizontalGroup(
            jpNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNetworkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBackNewtwork, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jpNetworkLayout.setVerticalGroup(
            jpNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNetworkLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBackNewtwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jpParent.add(jpNetwork, "card4");

        jpPlaywithPc.setBackground(new java.awt.Color(0, 0, 51));

        lPlayPC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lPlayPC.setForeground(new java.awt.Color(255, 255, 255));
        lPlayPC.setText("Play With PC");

        bBackPerson.setText("Back");
        bBackPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPlaywithPcLayout = new javax.swing.GroupLayout(jpPlaywithPc);
        jpPlaywithPc.setLayout(jpPlaywithPcLayout);
        jpPlaywithPcLayout.setHorizontalGroup(
            jpPlaywithPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlaywithPcLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bBackPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lPlayPC, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jpPlaywithPcLayout.setVerticalGroup(
            jpPlaywithPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlaywithPcLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpPlaywithPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPlayPC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBackPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jpParent.add(jpPlaywithPc, "Card2");

        getContentPane().add(jpParent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPlayNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayNetworkActionPerformed
        jpParent.removeAll();
        jpParent.add(jpNetwork);
        jpParent.repaint();
        jpParent.revalidate();
    }//GEN-LAST:event_bPlayNetworkActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bPlayWithPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayWithPcActionPerformed
        jpParent.removeAll();
        jpParent.add(jpPlaywithPc);
        jpParent.repaint();
        jpParent.revalidate();

    }//GEN-LAST:event_bPlayWithPcActionPerformed

    private void bPlayWithFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayWithFriendActionPerformed
        jpParent.removeAll();
        jpParent.add(jpPlayWithPerson);
        jpParent.repaint();
        jpParent.revalidate();
    }//GEN-LAST:event_bPlayWithFriendActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        jpParent.removeAll();
        jpParent.add(jpMainScreen);
        jpParent.repaint();
        jpParent.revalidate();

    }//GEN-LAST:event_bBackActionPerformed

    private void bBackNewtworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackNewtworkActionPerformed
        jpParent.removeAll();
        jpParent.add(jpMainScreen);
        jpParent.repaint();
        jpParent.revalidate();
    }//GEN-LAST:event_bBackNewtworkActionPerformed

    private void bBackPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackPersonActionPerformed
        jpParent.removeAll();
        jpParent.add(jpMainScreen);
        jpParent.repaint();
        jpParent.revalidate();
    }//GEN-LAST:event_bBackPersonActionPerformed

    private void jtUserNameUiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtUserNameUiAncestorAdded

        jtUserNameUi.setText(Model.getChUserName());
    }//GEN-LAST:event_jtUserNameUiAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bBackNewtwork;
    private javax.swing.JButton bBackPerson;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bPlayNetwork;
    private javax.swing.JButton bPlayWithFriend;
    private javax.swing.JButton bPlayWithPc;
    private javax.swing.JLabel jLDrawUi;
    private javax.swing.JLabel jLLoseUi;
    private javax.swing.JLabel jLWinUi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpMainScreen;
    private javax.swing.JPanel jpNetwork;
    private javax.swing.JPanel jpParent;
    private javax.swing.JPanel jpPlayWithPerson;
    private javax.swing.JPanel jpPlaywithPc;
    private javax.swing.JLabel jtUserNameUi;
    private javax.swing.JLabel lPlayPC;
    private javax.swing.JLabel lbScore;
    private javax.swing.JLabel lbUserName;
    // End of variables declaration//GEN-END:variables
}
